# Generated by Django 2.0.6 on 2018-06-30 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_owner', models.BooleanField()),
                ('purpose', models.CharField(max_length=400)),
                ('time', models.DateTimeField()),
                ('case_type', models.CharField(choices=[('SX', 'Sexual Violence'), ('EC', 'Economic'), ('EM', 'Emotional'), ('PY', 'Physical'), ('OT', 'Other')], max_length=2)),
                ('notes', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(null=True)),
                ('estimated_age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Center_service',
            fields=[
                ('health_center_service_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Centers',
            fields=[
                ('health_center_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Police_Station_service',
            fields=[
                ('police_station_service_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Police_Stations',
            fields=[
                ('police_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Safe_Spaces',
            fields=[
                ('safe_space_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=400)),
                ('internal', models.BooleanField()),
                ('calls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Calls')),
                ('safe_spaces', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Safe_Spaces')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Staff'),
        ),
        migrations.AddField(
            model_name='police_station_service',
            name='police_stations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Police_Stations'),
        ),
        migrations.AddField(
            model_name='police_station_service',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Service'),
        ),
        migrations.AddField(
            model_name='health_center_service',
            name='health_centers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Health_Centers'),
        ),
        migrations.AddField(
            model_name='health_center_service',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Service'),
        ),
        migrations.AddField(
            model_name='calls',
            name='clients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Client'),
        ),
    ]
