# Generated by Django 2.0.6 on 2018-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20180729_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('IP', 'In progress'), ('RE', 'Resolved')], default='IP', max_length=2),
        ),
    ]
