# Generated by Django 2.0.6 on 2018-06-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20180622_1101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Clinet_Detail',
        ),
    ]
