# Generated by Django 2.0.6 on 2018-08-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_auto_20180729_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=20)),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.District')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=20)),
                ('province_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Province')),
            ],
        ),
    ]
