# Generated by Django 2.0.6 on 2018-06-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_auto_20180622_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinet_detail',
            name='client',
        ),
        migrations.AddField(
            model_name='clinet',
            name='client_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Clinet_Detail'),
        ),
    ]
