# Generated by Django 2.0.6 on 2018-08-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_district_province_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='district_id',
        ),
        migrations.RemoveField(
            model_name='sector',
            name='province_id',
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Province'),
        ),
        migrations.AddField(
            model_name='sector',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.District'),
        ),
    ]
