# Generated by Django 2.0.6 on 2018-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0006_auto_20180626_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_center_service',
            name='center',
        ),
        migrations.RemoveField(
            model_name='health_center_service',
            name='service',
        ),
        migrations.RemoveField(
            model_name='police_station_service',
            name='station',
        ),
        migrations.AddField(
            model_name='health_center_service',
            name='name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='police_station_service',
            name='name',
            field=models.BooleanField(default=True),
        ),
    ]
