# Generated by Django 2.0.6 on 2018-06-26 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_auto_20180626_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_center_service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='police_station_service',
            name='name',
        ),
        migrations.AddField(
            model_name='health_center_service',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Health_Centers'),
        ),
        migrations.AddField(
            model_name='health_center_service',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Service'),
        ),
        migrations.AddField(
            model_name='police_station_service',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.Police_Stations'),
        ),
    ]
