# Generated by Django 2.0.6 on 2018-06-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0008_auto_20180626_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='call',
            new_name='calls',
        ),
    ]
