# Generated by Django 2.0.6 on 2018-06-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_auto_20180626_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='client',
            new_name='clients',
        ),
    ]
