# Generated by Django 2.0.6 on 2018-06-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_auto_20180626_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='police_station_service',
            old_name='service',
            new_name='services',
        ),
    ]
