# Generated by Django 2.0.6 on 2018-06-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_auto_20180626_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_center_service',
            old_name='center',
            new_name='health_centers',
        ),
        migrations.RenameField(
            model_name='police_station_service',
            old_name='station',
            new_name='police_stations',
        ),
    ]
