# Generated by Django 2.0.6 on 2018-06-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0012_auto_20180626_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_center_service',
            old_name='service',
            new_name='services',
        ),
    ]
