# Generated by Django 2.0.6 on 2018-06-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0013_auto_20180626_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='safe_space',
            new_name='safe_spaces',
        ),
    ]
