# Generated by Django 2.0.6 on 2018-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0014_auto_20180626_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
